services:
  storage:
    image: fsouza/fake-gcs-server:latest
    ports:
      - 3201:3201
    volumes:
      - gcs_data:/data
    command: [ "-scheme", "http", "-port", "3201", "-external-url", "http://localhost:3201", "-backend", "memory" ]
  pubsub:
    image: getalma/gcp-pubsub-emulator:latest
    ports:
      - 3202:8085
volumes:
  gcs_data:
